# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Action.create(points: 1, name: "Pray for ideas on how to share the gospel or to have missionary experiences. ")
Action.create(points: 1, name: "Learn someone‘s name ")
Action.create(points: 1, name: "Tell someone what church you belong to" )
Action.create(points: 1, name: "Tell someone about going to church when they ask what you did on the weekend" )
Action.create(points: 1, name: "Ask someone about their family")
Action.create(points: 1, name: "Perform an act of service" )
Action.create(points: 1, name: "Give someone a sincere compliment" )
Action.create(points: 1, name: "Hang pictures of Christ or temples in your home")
# 2 point activities 
Action.create( points: 2, name: "Share a church website, story or quote on Facebook, Twitter or Instagram" )
Action.create( points: 2, name: "Join a club, recreation group or volunteer project to meet new people" )
Action.create( points: 2, name: "Ask someone  they've ever heard of our church" )
Action.create( points: 2, name: "Put a Book of Mormon or church DVD on your desk" )
Action.create( points: 2, name: "Start a conversation with someone you don't know" )
Action.create( points: 2, name: "Invite friends to your home for dinner" )
Action.create( points: 2, name: "Tell someone about your mission or you child's or friend's mission" )
Action.create( points: 2, name: "Mention you're a Mormon to 2 people ín one day" )
Action.create( points: 2, name: "Read a Chapter of The Power of EverydaïMissionaries by Clayton Christensen")
# 3 point activities)
Action.create( points: 4, name: "Read paper scriptures in a public place (eg, Cafetería or waiting room)" )
Action.create( points: 4, name: "invite a friend to participate in a Church service project ")
Action.create( points: 4, name: "Leave a pass-along card with your tip a ta restaurant ")
Action.create( points: 4, name: "Invite friends to dinner with other members")
Action.create( points: 4, name: "Ask a friend about their church")
Action.create( points: 4, name: "Ask permission to pray for a friend who is struggiing ")
Action.create( points: 4, name: "Share a scripture or doctrine that applies to a friends situation ")
Action.create( points: 4, name: "Refer someone to mormon.org")
Action.create( points: 4, name: "Give someone a ride to church or to a church activity ")
Action.create( points: 4, name: "Ask the missionaries to teach you a lesson")

# 4 point things )

Action.create( points: 4, name: "Start a meaningful gospel conversation ")
Action.create( points: 4, name: "Bear your testimony of a gospel principle ")
Action.create( points: 4, name: "Make an \"I'm a Mormon\" profile on mormon.org" )
Action.create( points: 4, name: "Go with the missionaries to a teaching appointment")
Action.create( points: 4, name: "Share something you learned recently from scriptures or church with someone ")
Action.create( points: 4, name: "Invite a friend to help you fulfill your calling ")
Action.create( points: 4, name: "Tell someone about the addiction recovery program ")
Action.create( points: 4, name: "Write your testimony in a Book of Mormon for the missionaries to give out ")
Action.create( points: 4, name: "Invite a friend to hear you give a talk or lesson ")
Action.create( points: 4, name: "Share photos of a recent church history tour or temple visit with friends")
Action.create( points: 4, name: "Accompany the Full-Time missilonaries on a teaching appointment ")
Action.create( points: 4, name: "Invite a friend to a ward activity or FHE")

# 5 point things 
Action.create( points: 5, name: "Invite a friend to Sacrament Meeting ")
Action.create( points: 5, name: "Invite a friend over to your home for dinner with the missionaries ")
Action.create( points: 5, name: "Introduce friends from school or work to the missionaries ")
Action.create( points: 5, name: "Invite a friend to hear the first missionary lesson ín your home ")
Action.create( points: 5, name: "Refer a friend to the missionaries")
Action.create( points: 5, name: "Give a friend a Book of Mormon")
